version: "3"
services:
  api:
    container_name: thingYta-api
    restart: always
    build: .
    volumes:
    - ./src/:/usr/src/app/src
    ports:
      - "8000:8000"
    links:
      - mongo
  mongo:
    container_name: thingYota-mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
