version: "3"
services:
  api:
    container_name: thingYta-api
    restart: always
    build: .
    volumes:
    - ./src/:/usr/src/app/src
    ports:
      - "8000:8000"
    links:
      - mongo
      - mosquitto
  mongo:
    container_name: thingYota-mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  mosquitto:
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
