version: "3"
services:
  api:
    container_name: thingYta-api-standalone
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
    - ./src/:/usr/src/app/src
    ports:
      - "8000:8000"
    links:
      - mongo
      - mosquitto
  mongo:
    container_name: thingYota-mongodb-standalone
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  mosquitto:
    container_name: thingYota-mqtt-broker-standalone
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
