version: "2"
services:
  app:
    container_name: thingYta-api
    restart: always
    build: .
    ports:
      - "8000:8000"
    links:
      - mongo
  mongo:
    container_name: thingYota-mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
